# Generated by Django 3.2.9 on 2021-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.CharField(choices=[('20ºC', '20ºC'), ('30ºC', '30ºC'), ('40ºC', '40ºC'), ('50ºC', '50ºC'), ('60ºC', '60ºC'), ('70ºC', '70ºC'), ('80ºC', '80ºC'), ('90ºC', '90ºC'), ('100ºC', '100ºC'), ('110ºC', '110ºC')], max_length=5),
        ),
    ]
