# Generated by Django 3.2.9 on 2021-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentra', '0002_alter_consulta_temperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('naoh', models.FloatField()),
                ('T20', models.FloatField()),
                ('T30', models.FloatField()),
            ],
        ),
    ]
