# Generated by Django 3.2.9 on 2021-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentra', '0003_concentra'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fator',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='densidade',
            field=models.FloatField(),
        ),
    ]
