# Generated by Django 3.2.9 on 2021-11-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentra', '0004_auto_20211122_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='concentra',
            field=models.FloatField(default=0),
        ),
    ]
